// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IJWTProvider is an autogenerated mock type for the IJWTProvider type
type IJWTProvider struct {
	mock.Mock
}

type IJWTProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *IJWTProvider) EXPECT() *IJWTProvider_Expecter {
	return &IJWTProvider_Expecter{mock: &_m.Mock}
}

// GetJWTToken provides a mock function with no fields
func (_m *IJWTProvider) GetJWTToken() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetJWTToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IJWTProvider_GetJWTToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJWTToken'
type IJWTProvider_GetJWTToken_Call struct {
	*mock.Call
}

// GetJWTToken is a helper method to define mock.On call
func (_e *IJWTProvider_Expecter) GetJWTToken() *IJWTProvider_GetJWTToken_Call {
	return &IJWTProvider_GetJWTToken_Call{Call: _e.mock.On("GetJWTToken")}
}

func (_c *IJWTProvider_GetJWTToken_Call) Run(run func()) *IJWTProvider_GetJWTToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IJWTProvider_GetJWTToken_Call) Return(_a0 string, _a1 error) *IJWTProvider_GetJWTToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IJWTProvider_GetJWTToken_Call) RunAndReturn(run func() (string, error)) *IJWTProvider_GetJWTToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewIJWTProvider creates a new instance of IJWTProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIJWTProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *IJWTProvider {
	mock := &IJWTProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
