// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	subscription "github.com/sse-open/go-app-store-connect/appstoreserver/resource/subscription"
	appstoreserversubscription "github.com/sse-open/go-app-store-connect/appstoreserver/subscription"
	response "github.com/sse-open/go-app-store-connect/client/response"
	mock "github.com/stretchr/testify/mock"
)

// ISubscriptionService is an autogenerated mock type for the ISubscriptionService type
type ISubscriptionService struct {
	mock.Mock
}

type ISubscriptionService_Expecter struct {
	mock *mock.Mock
}

func (_m *ISubscriptionService) EXPECT() *ISubscriptionService_Expecter {
	return &ISubscriptionService_Expecter{mock: &_m.Mock}
}

// ExtendSubscriptionRenewalDate provides a mock function with given fields: ctx, originalTransactionId, req
func (_m *ISubscriptionService) ExtendSubscriptionRenewalDate(ctx context.Context, originalTransactionId string, req *subscription.ExtendRenewalDateRequest) (*subscription.ExtendRenewalDateResponse, *response.ClientResponse, error) {
	ret := _m.Called(ctx, originalTransactionId, req)

	if len(ret) == 0 {
		panic("no return value specified for ExtendSubscriptionRenewalDate")
	}

	var r0 *subscription.ExtendRenewalDateResponse
	var r1 *response.ClientResponse
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *subscription.ExtendRenewalDateRequest) (*subscription.ExtendRenewalDateResponse, *response.ClientResponse, error)); ok {
		return rf(ctx, originalTransactionId, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *subscription.ExtendRenewalDateRequest) *subscription.ExtendRenewalDateResponse); ok {
		r0 = rf(ctx, originalTransactionId, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*subscription.ExtendRenewalDateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *subscription.ExtendRenewalDateRequest) *response.ClientResponse); ok {
		r1 = rf(ctx, originalTransactionId, req)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*response.ClientResponse)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, *subscription.ExtendRenewalDateRequest) error); ok {
		r2 = rf(ctx, originalTransactionId, req)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ISubscriptionService_ExtendSubscriptionRenewalDate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtendSubscriptionRenewalDate'
type ISubscriptionService_ExtendSubscriptionRenewalDate_Call struct {
	*mock.Call
}

// ExtendSubscriptionRenewalDate is a helper method to define mock.On call
//   - ctx context.Context
//   - originalTransactionId string
//   - req *subscription.ExtendRenewalDateRequest
func (_e *ISubscriptionService_Expecter) ExtendSubscriptionRenewalDate(ctx interface{}, originalTransactionId interface{}, req interface{}) *ISubscriptionService_ExtendSubscriptionRenewalDate_Call {
	return &ISubscriptionService_ExtendSubscriptionRenewalDate_Call{Call: _e.mock.On("ExtendSubscriptionRenewalDate", ctx, originalTransactionId, req)}
}

func (_c *ISubscriptionService_ExtendSubscriptionRenewalDate_Call) Run(run func(ctx context.Context, originalTransactionId string, req *subscription.ExtendRenewalDateRequest)) *ISubscriptionService_ExtendSubscriptionRenewalDate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*subscription.ExtendRenewalDateRequest))
	})
	return _c
}

func (_c *ISubscriptionService_ExtendSubscriptionRenewalDate_Call) Return(_a0 *subscription.ExtendRenewalDateResponse, _a1 *response.ClientResponse, _a2 error) *ISubscriptionService_ExtendSubscriptionRenewalDate_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *ISubscriptionService_ExtendSubscriptionRenewalDate_Call) RunAndReturn(run func(context.Context, string, *subscription.ExtendRenewalDateRequest) (*subscription.ExtendRenewalDateResponse, *response.ClientResponse, error)) *ISubscriptionService_ExtendSubscriptionRenewalDate_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubscriptionStatus provides a mock function with given fields: ctx, transactionId, queryParams
func (_m *ISubscriptionService) GetSubscriptionStatus(ctx context.Context, transactionId string, queryParams *appstoreserversubscription.GetSubscriptionStatusQuery) (*subscription.StatusResponse, *response.ClientResponse, error) {
	ret := _m.Called(ctx, transactionId, queryParams)

	if len(ret) == 0 {
		panic("no return value specified for GetSubscriptionStatus")
	}

	var r0 *subscription.StatusResponse
	var r1 *response.ClientResponse
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *appstoreserversubscription.GetSubscriptionStatusQuery) (*subscription.StatusResponse, *response.ClientResponse, error)); ok {
		return rf(ctx, transactionId, queryParams)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *appstoreserversubscription.GetSubscriptionStatusQuery) *subscription.StatusResponse); ok {
		r0 = rf(ctx, transactionId, queryParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*subscription.StatusResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *appstoreserversubscription.GetSubscriptionStatusQuery) *response.ClientResponse); ok {
		r1 = rf(ctx, transactionId, queryParams)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*response.ClientResponse)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, *appstoreserversubscription.GetSubscriptionStatusQuery) error); ok {
		r2 = rf(ctx, transactionId, queryParams)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ISubscriptionService_GetSubscriptionStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubscriptionStatus'
type ISubscriptionService_GetSubscriptionStatus_Call struct {
	*mock.Call
}

// GetSubscriptionStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - transactionId string
//   - queryParams *appstoreserversubscription.GetSubscriptionStatusQuery
func (_e *ISubscriptionService_Expecter) GetSubscriptionStatus(ctx interface{}, transactionId interface{}, queryParams interface{}) *ISubscriptionService_GetSubscriptionStatus_Call {
	return &ISubscriptionService_GetSubscriptionStatus_Call{Call: _e.mock.On("GetSubscriptionStatus", ctx, transactionId, queryParams)}
}

func (_c *ISubscriptionService_GetSubscriptionStatus_Call) Run(run func(ctx context.Context, transactionId string, queryParams *appstoreserversubscription.GetSubscriptionStatusQuery)) *ISubscriptionService_GetSubscriptionStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*appstoreserversubscription.GetSubscriptionStatusQuery))
	})
	return _c
}

func (_c *ISubscriptionService_GetSubscriptionStatus_Call) Return(_a0 *subscription.StatusResponse, _a1 *response.ClientResponse, _a2 error) *ISubscriptionService_GetSubscriptionStatus_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *ISubscriptionService_GetSubscriptionStatus_Call) RunAndReturn(run func(context.Context, string, *appstoreserversubscription.GetSubscriptionStatusQuery) (*subscription.StatusResponse, *response.ClientResponse, error)) *ISubscriptionService_GetSubscriptionStatus_Call {
	_c.Call.Return(run)
	return _c
}

// MassExtendSubscriptionRenewalDates provides a mock function with given fields: ctx, req
func (_m *ISubscriptionService) MassExtendSubscriptionRenewalDates(ctx context.Context, req *subscription.MassExtendRenewalDateRequest) (*subscription.MassExtendRenewalDateResponse, *response.ClientResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for MassExtendSubscriptionRenewalDates")
	}

	var r0 *subscription.MassExtendRenewalDateResponse
	var r1 *response.ClientResponse
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *subscription.MassExtendRenewalDateRequest) (*subscription.MassExtendRenewalDateResponse, *response.ClientResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *subscription.MassExtendRenewalDateRequest) *subscription.MassExtendRenewalDateResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*subscription.MassExtendRenewalDateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *subscription.MassExtendRenewalDateRequest) *response.ClientResponse); ok {
		r1 = rf(ctx, req)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*response.ClientResponse)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, *subscription.MassExtendRenewalDateRequest) error); ok {
		r2 = rf(ctx, req)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ISubscriptionService_MassExtendSubscriptionRenewalDates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MassExtendSubscriptionRenewalDates'
type ISubscriptionService_MassExtendSubscriptionRenewalDates_Call struct {
	*mock.Call
}

// MassExtendSubscriptionRenewalDates is a helper method to define mock.On call
//   - ctx context.Context
//   - req *subscription.MassExtendRenewalDateRequest
func (_e *ISubscriptionService_Expecter) MassExtendSubscriptionRenewalDates(ctx interface{}, req interface{}) *ISubscriptionService_MassExtendSubscriptionRenewalDates_Call {
	return &ISubscriptionService_MassExtendSubscriptionRenewalDates_Call{Call: _e.mock.On("MassExtendSubscriptionRenewalDates", ctx, req)}
}

func (_c *ISubscriptionService_MassExtendSubscriptionRenewalDates_Call) Run(run func(ctx context.Context, req *subscription.MassExtendRenewalDateRequest)) *ISubscriptionService_MassExtendSubscriptionRenewalDates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*subscription.MassExtendRenewalDateRequest))
	})
	return _c
}

func (_c *ISubscriptionService_MassExtendSubscriptionRenewalDates_Call) Return(_a0 *subscription.MassExtendRenewalDateResponse, _a1 *response.ClientResponse, _a2 error) *ISubscriptionService_MassExtendSubscriptionRenewalDates_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *ISubscriptionService_MassExtendSubscriptionRenewalDates_Call) RunAndReturn(run func(context.Context, *subscription.MassExtendRenewalDateRequest) (*subscription.MassExtendRenewalDateResponse, *response.ClientResponse, error)) *ISubscriptionService_MassExtendSubscriptionRenewalDates_Call {
	_c.Call.Return(run)
	return _c
}

// NewISubscriptionService creates a new instance of ISubscriptionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewISubscriptionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ISubscriptionService {
	mock := &ISubscriptionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
