name: QA
on:
  workflow_call:

jobs:
  build-and-test:
    name: Compile and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.22'
          cache-dependency-path: go.sum

      - name: Lint and test
        run: |
          make install
          make lint
          make test